- name: require_auth_all_pages
  value_type: boolean
  value: 0
- name: registration_enabled
  value_type: boolean
  value: 1
- name: new_account_messages_enabled
  value_type: boolean
  value: 1
- name: make_trolls_lives_hard
  value_type: boolean
  value: 0
- name: auto_flagger_role
  value_type: boolean
  value: 1
- name: log_query_timings
  value_type: boolean
  value: 0
- name: min_wave_accuracy
  value_type: float
  value: 95.0
- name: min_wave_post_count
  value_type: number
  value: 10
- name: review_old_posts_days_threshold
  value_type: number
  value: 60
- name: review_old_posts_weight_threshold
  value_type: number
  value: 5
