production:
  adapter: redis
  url: redis://3.81.154.25:6379

local: &local
  adapter: redis
  timeout: 120
  url: redis://localhost:6378

test:
  adapter: redis
  timeout: 200
  url: redis://localhost:6379

development: *local
